events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    upstream user_service {
        server user-service:5000;
    }

    upstream product_service {
        server product-service:5001;
    }

    server {
        listen 80;
        server_name localhost; 

       
        client_max_body_size 20M;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/auth {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://user_service;
        }

        location /api/users {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://user_service;
        }

        location /api/products {
            proxy_pass http://product_service;
            
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
        }

        location /api/categories {
            proxy_pass http://product_service;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
        }

        error_page 502 /502.json;
        location = /502.json {
            return 502 '{"error": "Bad Gateway", "message": "The microservice is currently unavailable."}';
            default_type application/json;
        }
    }
}